export const types = [
    { name: 'Interceptions', value: 'Interceptions 6'},
    { name: 'Kickoff Yards', value: 'Kickoff-Yards 5'},
    { name: 'Passes Defended', value: 'Passes-Defended 15'},
    { name: 'Passing Touchdowns', value: 'Passing-Touchdowns 7'},
    { name: 'Passing Yards', value: 'Passing-Yards 0'},
    { name: 'Punt Yards', value: 'Punt-Yards 14'},
    { name: 'Quarterback Rating', value: 'Quarterback-Rating 8'},
    { name: 'Receiving Yards', value: 'Receiving-Yards 2'},
    { name: 'Receiving Touchdowns', value: 'Receiving-Touchdowns 11'},
    { name: 'Receptions', value: 'Receptions 10'},
    { name: 'Rushing Touchdowns', value: 'Rushing-Touchdowns 9'},
    { name: 'Rushing Yards', value: 'Rushing-Yards 1'},
    { name: 'Sacks', value: 'Sacks 4'},
    { name: 'Total Points', value: 'Total-Points 12'},
    { name: 'Total Tackles', value: 'Total-Tackles 3'},
    { name: 'Total Touchdowns', value: 'Total-Touchdowns 13'},
];